### ISSUE TITLE
Please provide "/benchmarks/datasets/" Folder

### ISSUE THREAD

**Issue by Tayyabkhalid** [MogicianXD/SeqFM#1]
Can you please provide the "/benchmarks/datasets/" Folder? Also need some guidance regarding what would be the steps if I want to use any other dataset?

**Comment by EagleYing** [comment]
同求数据集事例或是数据集生成步骤

**Comment by MogicianXD** [comment]
Please create the folder and put the datasets downloaded from their origin website. 
Filenames can remain unchanged. 
Run preprocess_xx.py to produce data files which will be input into torch.Dataset.
